name: Node.js Add CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Fix permissions for mocha
        run: chmod +x ./node_modules/.bin/mocha
        
      - name: Run Tests
        run: npm test
